# -*- coding: utf-8 -*-
"""下西洋棋-國王.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MtT9kWRHkxz9GZW3hbGLzrUSEarddSip
"""

x_1 , y_1 = input("").split()
x_2, y_2 = input("").split()
x1 , y1 ,x2,y2 = int(x_1) , int(y_1),int(x_2),int(y_2)

if x1<=7 and x1 >= 0 and x2<=7 and x2 >= 0 and y1<=7 and y1 >= 0 and y2<=7 and y2 >= 0:
  if x1 == x2 and y1 == y2:
    print("No")

  elif abs(x2 - x1) <=1 and abs(y2 - y1) <= 1:
    print('Yes')
  else:
    print('No')

else:
  print('No')